openapi: 3.0.0
info:
  version: 1.0.0
  title: Pokedex Application
  description: >-
    初代ポケモン151匹を表示するポケモン図鑑もどき。
paths:
  /:
    get:
      summary: トップページ取得
      description: |
      tags:
        - login
      responses:
        '200':
          description: トップページを返却する

  /register:
    get:
      summary: ログイン登録画面表示
      description: |
      tags:
        - login
      responses:
        '200':
          description: ログイン登録画面を返却する

  /register/save:
    post:
      summary: ログイン登録処理
      description: |
      tags:
        - login
      responses:
        '302':
          description: ログイン登録に成功する。「You have successfully registered our app!」が表示される。
        '200':
          description: ログイン登録に失敗する。「There is already an account registered with that email」が表示される。

  /login:
    get:
      summary: ログイン画面表示
      description: |
      tags:
        - login
      responses:
        '200':
          description: ログイン画面を返却する
    post:
      summary: ログイン処理
      description: |
      tags:
        - login
      responses:
        '302':
          description: 【ログインに成功時】/pictorial/listsに遷移する。【ログイン失敗時】 /login?errorに遷移し、「Invalid Email and Password.」が表示される。

  /logout:
    get:
      summary: ログアウト処理
      description: |
      tags:
        - logout
      responses:
        '200':
          description: ログアウトに成功する。/login?logoutに遷移し、「You have been logged out.」が表示される。

  /pictorial/lists:
    get:
      summary: ポケモン図鑑一覧表示
      description: |
      tags:
        - pictorial
      responses:
        '200':
          description: ポケモン図鑑一覧表示に成功する。

  /pictorial/lists/{id}:
    get:
      summary: ポケモン図鑑詳細表示
      description: |
      tags:
        - pictorial
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 【1 <= id <= 151】ポケモン図鑑詳細表示に成功する。/pictorial/lists/{id}に遷移する。【それ以外】ポケモン図鑑詳細表示に失敗する。/failsafe/failsafeのエラー画面に遷移する。

  /pictorial/lists/{id}/edit:
    get:
      summary: ポケモン図鑑編集表示
      description: |
      tags:
        - pictorial
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 【1 <= id <= 151】ポケモン図鑑編集表示に成功する。/pictorial/lists/{id}に遷移する。【それ以外】ポケモン図鑑編集表示に失敗する。/failsafe/failsafeのエラー画面に遷移する。

  /pictorial/lists/update:
    post:
      summary: ポケモン図鑑編集処理
      description: タイプ1、タイプ2のみ更新可能。更新値に制限はなくは空欄でも更新する。
      tags:
        - pictorial
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: integer
        - in: query
          name: name
          required: false
          schema:
            type: string
        - in: query
          name: type1
          required: false
          schema:
            type: string
        - in: query
          name: type2
          required: false
          schema:
            type: string
      responses:
        '302':
          description: ポケモン図鑑の編集に成功する。pictorial/lists/{id}に遷移する。

  /task/tasks:
    get:
      summary: ミッション一覧表示
      description: |
      tags:
        - task
      responses:
        '200':
          description: ポケモン図鑑一覧表示に成功する。

  /task/tasks/{id}:
    get:
      summary: ミッション詳細表示
      description: |
      tags:
        - task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 【idが存在する】ミッション詳細表示に成功する。【それ以外】ミッション詳細表示に失敗する。/failsafe/failsafeのエラー画面に遷移する。

  /task/tasks/{id}/edit:
    get:
      summary: ミッション編集画面表示
      description: |
      tags:
        - task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 【idが存在する】ミッション編集画面表示に成功する。【それ以外】ミッション編集画面表示に失敗する。/failsafe/failsafeのエラー画面に遷移する。

  /task/tasks/update:
    post:
      summary: ミッション編集処理
      description: ミッション内容のみ更新可能。更新値に制限はなくは空欄でも更新する。
      tags:
        - task
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: integer
        - in: query
          name: detail
          required: false
          schema:
            type: string
      responses:
        '302':
          description: ミッション詳細の編集に成功する。task/tasks/{id}に遷移する。

  /task/tasks/delete/{id}:
    get:
      summary: ミッション削除処理
      description: |
      tags:
        - task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '302':
          description: 【idが存在する時】ミッション削除に成功する。/task/tasksに遷移する。【それ以外】ミッション削除に失敗する。/failsafe/failsafeのエラー画面に遷移する。

  /task/register:
    get:
      summary: ミッション登録画面表示
      description: |
      tags:
        - task
      responses:
        '200':
          description: ミッション登録画面表示に成功する。

  /task/add:
    post:
      summary: ミッション登録処理
      description: ミッション内容のみ登録可能。更新値に制限はなくは空欄でも更新する。
      tags:
        - task
      parameters:
        - in: query
          name: addText
          required: true
          schema:
            type: string
      responses:
        '302':
          description: ミッション登録に成功する。task/tasksに遷移する。
