DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS task;

CREATE TABLE pokemon (
 id int unsigned AUTO_INCREMENT,
 name VARCHAR(20) NOT NULL,
 type1 VARCHAR(20) NOT NULL,
 type2 VARCHAR(20),
 PRIMARY KEY(id)
);

CREATE TABLE task (
 id int unsigned AUTO_INCREMENT,
 detail VARCHAR(20) NOT NULL,
 PRIMARY KEY(id)
);

INSERT INTO pokemon (id, name, type1, type2) VALUES (1, "フシギダネ", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (2, "フシギソウ", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (3, "フシギバナ", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (4, "ヒトカゲ", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (5, "リザード", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (6, "リザードン", "ほのお", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (7, "ゼニガメ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (8, "カメール", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (9, "カメックス", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (10, "キャタピー", "むし", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (11, "トランセル", "むし", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (12, "バタフリー", "むし", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (13, "ビードル", "むし", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (14, "コクーン", "むし", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (15, "スピアー", "むし", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (16, "ポッポ", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (17, "ピジョン", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (18, "ピジョット", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (19, "コラッタ", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (20, "ラッタ", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (21, "オニスズメ", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (22, "オニドリル", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (23, "アーボ", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (24, "アーボック", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (25, "ピカチュウ", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (26, "ライチュウ", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (27, "サンド", "じめん", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (28, "サンドパン", "じめん", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (29, "ニドラン♀", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (30, "ニドリーナ", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (31, "ニドクイン", "どく", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (32, "ニドラン♂", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (33, "ニドリーノ", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (34, "ニドキング", "どく", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (35, "ピッピ", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (36, "ピクシー", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (37, "ロコン", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (38, "キュウコン", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (39, "プリン", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (40, "プクリン", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (41, "ズバット", "どく", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (42, "ゴルバット", "どく", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (43, "ナゾノクサ", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (44, "クサイハナ", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (45, "ラフレシア", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (46, "パラス", "むし", "くさ");
INSERT INTO pokemon (id, name, type1, type2) VALUES (47, "パラセクト", "むし", "くさ");
INSERT INTO pokemon (id, name, type1, type2) VALUES (48, "コンパン", "むし", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (49, "モルフォン", "むし", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (50, "ディグダ", "じめん", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (51, "ダグトリオ", "じめん", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (52, "ニャース", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (53, "ペルシアン", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (54, "コダック", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (55, "ゴルダック", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (56, "マンキー", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (57, "オコリザル", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (58, "ガーディ", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (59, "ウインディ", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (60, "ニョロモ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (61, "ニョロゾ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (62, "ニョロボン", "みず", "かくとう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (63, "ケーシィ", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (64, "ユンゲラー", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (65, "フーディン", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (66, "ワンリキー", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (67, "ゴーリキー", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (68, "カイリキー", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (69, "マダツボミ", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (70, "ウツドン", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (71, "ウツボット", "くさ", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (72, "メノクラゲ", "みず", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (73, "ドククラゲ", "みず", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (74, "イシツブテ", "いわ", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (75, "ゴローン", "いわ", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (76, "ゴローニャ", "いわ", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (77, "ポニータ", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (78, "ギャロップ", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (79, "ヤドン", "みず", "エスパー");
INSERT INTO pokemon (id, name, type1, type2) VALUES (80, "ヤドラン", "みず", "エスパー");
INSERT INTO pokemon (id, name, type1, type2) VALUES (81, "コイル", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (82, "レアコイル", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (83, "カモネギ", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (84, "ドードー", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (85, "ドードリオ", "ノーマル", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (86, "パウワウ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (87, "ジュゴン", "みず", "こおり");
INSERT INTO pokemon (id, name, type1, type2) VALUES (88, "ベトベター", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (89, "ベトベトン", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (90, "シェルダー", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (91, "パルシェン", "みず", "こおり");
INSERT INTO pokemon (id, name, type1, type2) VALUES (92, "ゴース", "ゴースト", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (93, "ゴースト", "ゴースト", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (94, "ゲンガー", "ゴースト", "どく");
INSERT INTO pokemon (id, name, type1, type2) VALUES (95, "イワーク", "いわ", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (96, "スリープ", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (97, "スリーパー", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (98, "クラブ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (99, "キングラー", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (100, "ビリリダマ", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (101, "マルマイン", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (102, "タマタマ", "くさ", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (103, "ナッシー", "くさ", "エスパー");
INSERT INTO pokemon (id, name, type1, type2) VALUES (104, "カラカラ", "じめん", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (105, "ガラガラ", "じめん", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (106, "サワムラー", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (107, "エビワラー", "かくとう", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (108, "ベロリンガ", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (109, "ドガース", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (110, "マタドガス", "どく", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (111, "サイホーン", "いわ", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (112, "サイドン", "いわ", "じめん");
INSERT INTO pokemon (id, name, type1, type2) VALUES (113, "ラッキー", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (114, "モンジャラ", "くさ", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (115, "ガルーラ", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (116, "タッツー", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (117, "シードラ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (118, "トサキント", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (119, "アズマオウ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (120, "ヒトデマン", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (121, "スターミー", "みず", "エスパー");
INSERT INTO pokemon (id, name, type1, type2) VALUES (122, "バリヤード", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (123, "ストライク", "むし", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (124, "ルージュラ", "こおり", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (125, "エレブー", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (126, "ブーバー", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (127, "カイロス", "むし", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (128, "ケンタロス", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (129, "コイキング", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (130, "ギャラドス", "みず", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (131, "ラプラス", "みず", "こおり");
INSERT INTO pokemon (id, name, type1, type2) VALUES (132, "メタモン", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (133, "イーブイ", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (134, "シャワーズ", "みず", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (135, "サンダース", "でんき", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (136, "ブースター", "ほのお", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (137, "ポリゴン", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (138, "オムナイト", "みず", "いわ");
INSERT INTO pokemon (id, name, type1, type2) VALUES (139, "オムスター", "みず", "いわ");
INSERT INTO pokemon (id, name, type1, type2) VALUES (140, "カブト", "みず", "いわ");
INSERT INTO pokemon (id, name, type1, type2) VALUES (141, "カブトプス", "みず", "いわ");
INSERT INTO pokemon (id, name, type1, type2) VALUES (142, "プテラ", "いわ", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (143, "カビゴン", "ノーマル", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (144, "フリーザー", "こおり", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (145, "サンダー", "でんき", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (146, "ファイヤー", "ほのお", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (147, "ミニリュウ", "ドラゴン", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (148, "ハクリュー", "ドラゴン", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (149, "カイリュー", "ドラゴン", "ひこう");
INSERT INTO pokemon (id, name, type1, type2) VALUES (150, "ミュウツー", "エスパー", "");
INSERT INTO pokemon (id, name, type1, type2) VALUES (151, "ミュウ", "エスパー", "");

INSERT INTO task (id, detail) VALUES (1, "グレーバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (2, "ブルーバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (3, "オレンジバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (4, "レインボーバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (5, "ピンクバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (6, "ゴールドバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (7, "クリムゾンバッジを入手せよ");
INSERT INTO task (id, detail) VALUES (8, "グリーンバッジを入手せよ");
